[package]
name = "edenx"
version = "1.0.0"
upgrade_policy = "compatible"

[addresses]
edenx = "_"

[dev-addresses]


[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "mainnet" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token-objects/", rev = "mainnet" }

[dev-dependencies]